[[Xorg_xtrans]]
arch = "aarch64"
git-tree-sha1 = "3bcb948420b2c63d444ecd872c0f116d28c228d6"
libc = "glibc"
os = "linux"

    [[Xorg_xtrans.download]]
    sha256 = "971a62aa0c61286ef21332972e40c70ef67f9ec57514352297fb7775f847cc12"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xtrans_jll.jl/releases/download/Xorg_xtrans-v1.4.0+2/Xorg_xtrans.v1.4.0.aarch64-linux-gnu.tar.gz"
[[Xorg_xtrans]]
arch = "aarch64"
git-tree-sha1 = "4657457f35c947958d3a4388851149d79c6b1a23"
libc = "musl"
os = "linux"

    [[Xorg_xtrans.download]]
    sha256 = "a1840461af4388d77613cab225b7fdb170ec6cd9eb9d9544b8d2344e440686d2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xtrans_jll.jl/releases/download/Xorg_xtrans-v1.4.0+2/Xorg_xtrans.v1.4.0.aarch64-linux-musl.tar.gz"
[[Xorg_xtrans]]
arch = "armv7l"
git-tree-sha1 = "f15ad4487d618b7189f2477384a3e83bba0ff58d"
libc = "glibc"
os = "linux"

    [[Xorg_xtrans.download]]
    sha256 = "660d77b41f0ca4188f4db8a36e2c7845d9afc630cbb6abc400ef6be2fd025f2b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xtrans_jll.jl/releases/download/Xorg_xtrans-v1.4.0+2/Xorg_xtrans.v1.4.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_xtrans]]
arch = "armv7l"
git-tree-sha1 = "cfcf51bfedd94e6f8f0588af2800ff474fef185e"
libc = "musl"
os = "linux"

    [[Xorg_xtrans.download]]
    sha256 = "dbb07eac86bc65f8dd2edb8a4a29ad4ea03f8a4cb46d90296a1ccd0e082046ba"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xtrans_jll.jl/releases/download/Xorg_xtrans-v1.4.0+2/Xorg_xtrans.v1.4.0.armv7l-linux-musleabihf.tar.gz"
[[Xorg_xtrans]]
arch = "i686"
git-tree-sha1 = "0309665b677da127ba79d8568ba102fd0ad9afb4"
libc = "glibc"
os = "linux"

    [[Xorg_xtrans.download]]
    sha256 = "08415e8777f851f81764781f6c2d4199918a40954914ba36ed20a1e8cd60db1e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xtrans_jll.jl/releases/download/Xorg_xtrans-v1.4.0+2/Xorg_xtrans.v1.4.0.i686-linux-gnu.tar.gz"
[[Xorg_xtrans]]
arch = "i686"
git-tree-sha1 = "28e0757b47d14cdb5bc555e5014a66deb6848688"
libc = "musl"
os = "linux"

    [[Xorg_xtrans.download]]
    sha256 = "2b8ac6db621aacbdceebec52af0bb2df177554ea94e157df047089e37442727c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xtrans_jll.jl/releases/download/Xorg_xtrans-v1.4.0+2/Xorg_xtrans.v1.4.0.i686-linux-musl.tar.gz"
[[Xorg_xtrans]]
arch = "powerpc64le"
git-tree-sha1 = "ea54835873bc1f314a49cb15771b716ecb0839f3"
libc = "glibc"
os = "linux"

    [[Xorg_xtrans.download]]
    sha256 = "c2d1ab2840a001dfcbac3fbefafab2f7a976b5fb075ee5265c6a259fbb273d49"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xtrans_jll.jl/releases/download/Xorg_xtrans-v1.4.0+2/Xorg_xtrans.v1.4.0.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xtrans]]
arch = "x86_64"
git-tree-sha1 = "45f6b81caf89f7e08b1253217d7deb82d0af6822"
libc = "glibc"
os = "linux"

    [[Xorg_xtrans.download]]
    sha256 = "14a4b2c4afb360c15c49beabe614555af305a5d1d5328f2fb37de22d682ad70e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xtrans_jll.jl/releases/download/Xorg_xtrans-v1.4.0+2/Xorg_xtrans.v1.4.0.x86_64-linux-gnu.tar.gz"
[[Xorg_xtrans]]
arch = "x86_64"
git-tree-sha1 = "98fa8e5372d6975a4cd32a44ec94050bea8d2268"
libc = "musl"
os = "linux"

    [[Xorg_xtrans.download]]
    sha256 = "c72fd3f3b7397407e7dd630b96a94ca9e6899a5e21aa61868d6740ec51c5656d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xtrans_jll.jl/releases/download/Xorg_xtrans-v1.4.0+2/Xorg_xtrans.v1.4.0.x86_64-linux-musl.tar.gz"
[[Xorg_xtrans]]
arch = "x86_64"
git-tree-sha1 = "6dd5a59d94de9e566c32ac89d7a9a0cf352ccb4e"
os = "freebsd"

    [[Xorg_xtrans.download]]
    sha256 = "7c31f9a24a738ce0295b3fe3fa8df817f0bfc6497dd11245a7aa5955ccaa67a8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xtrans_jll.jl/releases/download/Xorg_xtrans-v1.4.0+2/Xorg_xtrans.v1.4.0.x86_64-unknown-freebsd11.1.tar.gz"
