[[Libuuid]]
arch = "aarch64"
git-tree-sha1 = "876c86e0eece2afa2532ff5b5ff656f6e6316497"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "686d47c5e7b1963842e2177d86ea9dd1fe2574b798287520db5f1ab002824191"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.36.0+0/Libuuid.v2.36.0.aarch64-linux-gnu.tar.gz"
[[Libuuid]]
arch = "aarch64"
git-tree-sha1 = "8fe23cd8be8c334a8d869a178ed06c6d9ced19a1"
libc = "musl"
os = "linux"

    [[Libuuid.download]]
    sha256 = "7f357f56cd620a4c898284142861c0846b6640ed1945aafbc5611603a9f4dab5"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.36.0+0/Libuuid.v2.36.0.aarch64-linux-musl.tar.gz"
[[Libuuid]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "070fee5f00d1590414b9daab48b3be180ab72a20"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "55652b340521859a35684057d009d5e799392e29c2aa0e307d445e27b3d0d031"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.36.0+0/Libuuid.v2.36.0.armv6l-linux-gnueabihf.tar.gz"
[[Libuuid]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9dcbe56f655c091d43eb52cd03fafe9ae40e8a54"
libc = "musl"
os = "linux"

    [[Libuuid.download]]
    sha256 = "f42518e975148dcab92177742cfa701ed64dd67b884381f096f7c2cae9e248fd"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.36.0+0/Libuuid.v2.36.0.armv6l-linux-musleabihf.tar.gz"
[[Libuuid]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "12b7cc0f3031f5dbeed21fef6d8e9826f31c518c"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "514402cae20bf684bb1904b76b858a88c7cf451aa0db02194d2c93bf1222dca2"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.36.0+0/Libuuid.v2.36.0.armv7l-linux-gnueabihf.tar.gz"
[[Libuuid]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "668a49976b4912037a3747160d5280f821dfd5a6"
libc = "musl"
os = "linux"

    [[Libuuid.download]]
    sha256 = "bdcce1c832f2d95c41d771e0a0564e27828c0b605f646682c8879dd757f5d193"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.36.0+0/Libuuid.v2.36.0.armv7l-linux-musleabihf.tar.gz"
[[Libuuid]]
arch = "i686"
git-tree-sha1 = "499cafb090612594a2d020ccf8cb730414474404"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "60362d60f92213d36cc66a965fcdce8c8e8e8d89a7835e24a93bbf3537a23d19"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.36.0+0/Libuuid.v2.36.0.i686-linux-gnu.tar.gz"
[[Libuuid]]
arch = "i686"
git-tree-sha1 = "240f837b9b00f3fdaf7a12e628ea121cb394223b"
libc = "musl"
os = "linux"

    [[Libuuid.download]]
    sha256 = "f9014f120e5dfa86da6222f374834f9a93bea1618a6afaa534a76e9dd90f9906"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.36.0+0/Libuuid.v2.36.0.i686-linux-musl.tar.gz"
[[Libuuid]]
arch = "powerpc64le"
git-tree-sha1 = "eab38fb4d8b7e207e635270fa894aaf108ef448a"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "fe321255d850bbc013cc296c1b3ec772e6a7c687b464ffa1a0045571a8d28d9e"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.36.0+0/Libuuid.v2.36.0.powerpc64le-linux-gnu.tar.gz"
[[Libuuid]]
arch = "x86_64"
git-tree-sha1 = "2b77b304b0975d15bd5aeb4d1d5097ac6256ea3c"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "b541ec7a6ebf63916be7142507a363d744e9ed138138272e5bf08774899e866d"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.36.0+0/Libuuid.v2.36.0.x86_64-linux-gnu.tar.gz"
[[Libuuid]]
arch = "x86_64"
git-tree-sha1 = "2beeeee958a2f86d2e390ea32f02cfc586545bb6"
libc = "musl"
os = "linux"

    [[Libuuid.download]]
    sha256 = "9cc4c6eb7642aa7df82280e17486562957a9e71192461c6094860dd8e72155cf"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.36.0+0/Libuuid.v2.36.0.x86_64-linux-musl.tar.gz"
[[Libuuid]]
arch = "x86_64"
git-tree-sha1 = "637058ca67f157b1ba4997683a736f8908b0dc57"
os = "freebsd"

    [[Libuuid.download]]
    sha256 = "99594b3e20eb07809e8aa164c818d6c3415f5edb0a427c79b379dc35df9b51c6"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.36.0+0/Libuuid.v2.36.0.x86_64-unknown-freebsd.tar.gz"
