[[Xorg_libpthread_stubs]]
arch = "aarch64"
git-tree-sha1 = "a7148150741aacc3cb104769cee55207ae3644d2"
libc = "glibc"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "923afadcd23bfb9aa3e48521636000afa21f1a059115e10d22ac0731d68ba1fc"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+2/Xorg_libpthread_stubs.v0.1.0.aarch64-linux-gnu.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "aarch64"
git-tree-sha1 = "988bca09dcb038d3c88acb07725301b00df48f07"
libc = "musl"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "c8421b5c1f242d79c3086a02f523cfdeeacfb2be7b9514436c9a752eb4a9037b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+2/Xorg_libpthread_stubs.v0.1.0.aarch64-linux-musl.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "armv7l"
git-tree-sha1 = "f6fcd9ba8ee00378296d2a92618aef748ab9bbff"
libc = "glibc"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "cd7af3fca8944556b0467cd1b85028ac8aa6433763fefdf67e879cc8b09c7eae"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+2/Xorg_libpthread_stubs.v0.1.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "armv7l"
git-tree-sha1 = "cfad91f3ee7ab721dda64fb10678a78aff9993ed"
libc = "musl"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "3f65fbf41a81ab95092c9cce600af3eef71aa38a6298a50c00f7ad13687ab06d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+2/Xorg_libpthread_stubs.v0.1.0.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "i686"
git-tree-sha1 = "1a18f9ad193e6a50e1756a5248de22823131e99b"
libc = "glibc"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "db0c2cc8a047b6ef969de438633b7bf84c661f8296704155ec230e1fb37fc809"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+2/Xorg_libpthread_stubs.v0.1.0.i686-linux-gnu.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "i686"
git-tree-sha1 = "534d3c7bac35baf8684413dcd62266bfcb5ed18a"
libc = "musl"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "9dd653522da6f3dfa81b68e7cb39db20fe57c55f901741c7f004d705e035f7d0"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+2/Xorg_libpthread_stubs.v0.1.0.i686-linux-musl.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "powerpc64le"
git-tree-sha1 = "669ad78445868bafbed579272c94537c16339d12"
libc = "glibc"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "211e94263ddcefd85d7e650c646ac899ec7b0649feaf5dd7e329ad4e60408def"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+2/Xorg_libpthread_stubs.v0.1.0.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "x86_64"
git-tree-sha1 = "aa3e93661fefff04200a3d0099cfdd1b5fc0ded3"
libc = "glibc"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "8cba18f2080eb2cb0ee20447faa565b568f65c82505027fc558f34400e42bd0b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+2/Xorg_libpthread_stubs.v0.1.0.x86_64-linux-gnu.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "x86_64"
git-tree-sha1 = "d05beffcbfe11b07a476c11cbe77996eee0c0aab"
libc = "musl"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "9cdf2ca2b2ab71927177ff69a564c3e2c0a8d4ea4f3f1c97d74bf9a5bb7e01fd"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+2/Xorg_libpthread_stubs.v0.1.0.x86_64-linux-musl.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "x86_64"
git-tree-sha1 = "1f8f3dcba12771add863183abb8c36ea445f220e"
os = "freebsd"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "df0899552c2774d0d21feb8e2144b2433a224f243437dfa9ae6d60749791efc1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+2/Xorg_libpthread_stubs.v0.1.0.x86_64-unknown-freebsd11.1.tar.gz"
