[[Libglvnd]]
arch = "aarch64"
git-tree-sha1 = "894c10e3ec87babd6234f51d21599f8a59777225"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "6b4f6a56e894c52611300da440ae4cf87be14124bb2dcee800b4dc306f5b1558"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+2/Libglvnd.v1.3.0.aarch64-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "aarch64"
git-tree-sha1 = "ad3c0695de5b657010d82c55dc661280260e8d52"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "be1b868c23e7c767e5d06cf8997147581e146a97943bfffab1593debbecb1dd1"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+2/Libglvnd.v1.3.0.aarch64-linux-musl.tar.gz"
[[Libglvnd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "61a216bc6ef39eb8c319925b96fe107d2f2db6e8"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "e3edc36aef6f4aa342790b5297d3a3da0f30cfaf5275e91592d31b9678672191"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+2/Libglvnd.v1.3.0.armv7l-linux-gnueabihf.tar.gz"
[[Libglvnd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0ec18e5e69e57f11fbda004d33ded1b06c111a38"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "597a7bd8029f6da43f5221b9e27d75f9967b4ce6d806d9da5c1e3f49c604213d"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+2/Libglvnd.v1.3.0.armv7l-linux-musleabihf.tar.gz"
[[Libglvnd]]
arch = "i686"
git-tree-sha1 = "538acb3cf2e51980662443b87d12f0e1df991196"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "d0635e70fedb05dce76672c27204c70144c14b8ace9ff18edfcbc2f0b28da261"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+2/Libglvnd.v1.3.0.i686-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "i686"
git-tree-sha1 = "5e73cc32206548c08edd275ed3ceac67d4b9e475"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "333c65e10d0c5bf2d550a51bd07758c3707f7b4aca48d8802abf7dd1347bbba9"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+2/Libglvnd.v1.3.0.i686-linux-musl.tar.gz"
[[Libglvnd]]
arch = "powerpc64le"
git-tree-sha1 = "a135b4a49271d869c645949c70f3b09b21831590"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "60fa0af09a273794704a6a6b4c4d9db658832e2f935842dfde366237dd556ddf"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+2/Libglvnd.v1.3.0.powerpc64le-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "a84cc58d5161b950f268bb562e105bbbf4d6004a"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "dc7ded52add5752bb4ca5c9f917575afa59f0018efb1200dfaf994607c00bd18"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+2/Libglvnd.v1.3.0.x86_64-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "2f442efbdbfccc5062ca93da00cc18d0ac7cd72f"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "1ce04aedfe0c2434913a6050c768c5f151db96453fdf632cb77fabc468d9425f"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+2/Libglvnd.v1.3.0.x86_64-linux-musl.tar.gz"
[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "6c142e40b0275f32a28f53055fa7d596097ee5a6"
os = "freebsd"

    [[Libglvnd.download]]
    sha256 = "878875bfe431265d1b0a87415d6eead632dd40585a34cb6d9338514c076e2353"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+2/Libglvnd.v1.3.0.x86_64-unknown-freebsd.tar.gz"
