# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - freebsd
julia:
  - 1.3
  - 1.4
  - 1.5
  - nightly
matrix:
  # allow_failures:
  #   - julia: nightly
  fast_finish: true
notifications:
  email: false

branches:
  only:
  - master
  - gh-pages # For building documentation
  - /^testing-.*$/ # testing branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

cache:
  directories:
  - $HOME/.julia/artifacts
