[[Blosc]]
arch = "aarch64"
git-tree-sha1 = "f390f31f2133520e2005ec9cf45b695804485599"
os = "macos"

    [[Blosc.download]]
    sha256 = "04b60b3a797aed04f033d1f45859a3db559149896b121881000e7a350bf772b9"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.aarch64-apple-darwin.tar.gz"
[[Blosc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45a8564efe771e0430abc9465ede14d4c759c7cb"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "323b35177df3c267c5a987c23529efca5ea2d0b79efa0b597e4882f243cb9186"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Blosc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a63df688ba0e7f409abc84af2ee1898e3b48b1d"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "ecf4643e2cb5610338a98ff5c37ae517ba378311c0b54b5062e5651cd56ad422"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Blosc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61353f6d0c11d26424fa7d5a5850e92784ade4be"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "66dcff2ab4acd61a8028de002b90d1d43c9e025a109a179f2567502cb163b4be"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.aarch64-linux-musl-cxx03.tar.gz"
[[Blosc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bf48b642ac5614640c3afb0512b0e63798d813a"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "245da18f50fa27488adb9fe5232ad6ea07a73b1b7bbe35d16930899669e6cfdf"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.aarch64-linux-musl-cxx11.tar.gz"
[[Blosc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3fa2d6ec097ab231551fb55690875c36f7e247a"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "8480a259e3cbb7415d59bb575e2b89fd6ed04c7eee4f1c0fefb812154fa20350"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Blosc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8203941630952856692380abb09ac8b37dd77831"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "dee67884c779cdeb837dc046bf15c522ecb2cc96eecac48c2e1110e77ab478ed"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Blosc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "73e996503043c2c4eadac5c35a0f26e770068941"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "f166044472cd0eca4e4db2e9b06db7b3ca2f22176ca6868b0b32f419b2a99cb0"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Blosc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bcf54bd9cf9f3d25d2eb94f9756db54b9a4cefbe"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "48f0b3ac9d7072018c1e49b6d02405b1b59219d63338a8a05a13f01966edc9ce"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62b6a3d479b10cb334ccbac279a6d2fd2960bb53"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "afa122f2528c93672c3999c4d042f8184a7e5ac524b57ecd09ea9e108417314d"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3430269d54210d8e04cb1e2a528eb3010d384762"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "d00b8dd20000775b41e98d57396ca8f5b66c4a920a6a3606ccdb50b4f6eae6ec"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d66bb18b76e708e31a999385d2d65e6dcaa39c53"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "07422d53c1bfbbd2be0c9e22d5333fb8d431f0fa8c980ba4d01df7a5ae6d1a94"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94cd8380ff14d61b779ef32d2b77b732f42fab7b"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "65ccbc702bd4a4191e432446bba8bd2d93e626b3fe12eef9579dac3c74cab8b2"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e64b181562ed04763f98b02e1b0f702b52546795"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "7f95686a7c46e321a417b68fa784e859f96d377b57deaf4353a0806a165fa0e2"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.i686-linux-gnu-cxx03.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f3558b40557ca259de3e979b3f6dbdf2b880c98"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "b62d91346c3c61f959ccbc4f8fe60d02961c3e6a90db24750c03b337b0b58b89"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.i686-linux-gnu-cxx11.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18c9c6a2cf04b8616976cba105cc5e809758b31d"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "48f74c3a27a7fde672ed33f4e79036419b6a05d26f11c0bee43e7b51b88d522f"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.i686-linux-musl-cxx03.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dcce5155cf70c7f1c3347729c6f5d9db862fa76"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "68c09c1391ba2a7ab53d12089b6e8d488d08dc7fab346f14c015f6e4fba0cbac"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.i686-linux-musl-cxx11.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8361fe35cc83706f03183600261153b42f50d812"
os = "windows"

    [[Blosc.download]]
    sha256 = "d94bf2d630948b9050a0d635cebe81091a9946eec2e510ef60b9d1eaf9a19480"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.i686-w64-mingw32-cxx03.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa22a57a347ffaade67dfd06be519be25ef43a1f"
os = "windows"

    [[Blosc.download]]
    sha256 = "59c70ec86539428d4488cf3174e315226f2a69419b454040802ecccfcaa8a4ac"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.i686-w64-mingw32-cxx11.tar.gz"
[[Blosc]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5fc52ac19f823e80c33977cb6bb182d65fef44d2"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "9cac37eeb2e75c0adb8c64ec0b4ef55e11252d8fd2faac196ccff8b29cf77d2e"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Blosc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b50fd3b014aa1e53256a8167ac6a4fd8a2b5d175"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "49813fef2a5b0f559e5dcd80522ed85779c4a914f8d92993d1d8c5fddcea61a8"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "8959ebf4a7266de2e32e9e0dcf507bbc75ec536d"
os = "macos"

    [[Blosc.download]]
    sha256 = "73163629abe4ac0c945cc929138cab89638d9d876f12d24643c93d30b6650355"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.x86_64-apple-darwin.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f0502f5960745be89a024c9a3457cc9ed4ab579"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "c68ca3f27279ddd7aae162d461826a5503231c5fb5b4022066c92af7054fb383"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9574d9cc70f1903e853bc83db7e7aee45ae7ec9a"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "1af4c818948ad677a5cd4f9a8a6a72f0b86e712738b2be1f604dcaf79d1b8c5e"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f8a05454cab27e62f0766df296f13497bf81473"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "878e34bc6fb55c2bd0584fc0d7ea2d545d02ceae33866b087b22afed90690ac6"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.x86_64-linux-musl-cxx03.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a38734d1cdeba8ba1075cdbc1cd5332040040de"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "90657bb5eeff0a10cd724f0c5a82293ac422c6b841dce953ca1460b430c2a37e"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.x86_64-linux-musl-cxx11.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "4c03f1b37f34d6357017890284526b3471b355e5"
os = "freebsd"

    [[Blosc.download]]
    sha256 = "506e5037f2063a97e568b273f7409c058ab89f055da0c4eb4e6f25c9708cf223"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.x86_64-unknown-freebsd.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7b198e5891f23079f84595263d6d6c6b7905083"
os = "windows"

    [[Blosc.download]]
    sha256 = "5df899cba5fb0484c3ead84e30fdbb9163ae126b8a40fc28ef6b7cd7a8a8f753"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93bcf5364836eebf55e9495e82486b8803552c1b"
os = "windows"

    [[Blosc.download]]
    sha256 = "7d74e9ec18c5d1d1cd45b538090a672627b056dbd7d00325ad3420ccbcc07bc0"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.1+0/Blosc.v1.21.1.x86_64-w64-mingw32-cxx11.tar.gz"
