[[Xorg_xkeyboard_config]]
arch = "aarch64"
git-tree-sha1 = "563b751229dc4a61fdd4995ecd2a90bc61d752e6"
libc = "glibc"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "cf64f4eaaebdbdc90a7a19de6f003a35a93a7ee4c3b208d977708c5191e7c2c6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+3/Xorg_xkeyboard_config.v2.27.0.aarch64-linux-gnu.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "aarch64"
git-tree-sha1 = "1779f60a24d575a63addb1dbd096fea1188c79d9"
libc = "musl"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "2e42d517a997724ef3a31404243be9e3469b1fcc3d8b9658f0d153e755285786"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+3/Xorg_xkeyboard_config.v2.27.0.aarch64-linux-musl.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "armv7l"
git-tree-sha1 = "65e19158c8effb68f8668fbd3980052847ce199c"
libc = "glibc"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "d26d9055d09dc0e5a60552147405b7da8be0d95731edd7bf7aa99fffe242c017"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+3/Xorg_xkeyboard_config.v2.27.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "armv7l"
git-tree-sha1 = "61073f045fb4791e94f6873da0ce2321e5af92af"
libc = "musl"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "dbd239ea6da9879b2cb48538944b9fd16c8b5a52a8526f3f8fcadead10469ab5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+3/Xorg_xkeyboard_config.v2.27.0.armv7l-linux-musleabihf.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "i686"
git-tree-sha1 = "8fd5eaac9b5c8690220195c451cd4a47ce8fe2fc"
libc = "glibc"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "ea2bffedf9e7725e76ea6b9de61d353a1bb203e74985d7d139db2875437a1334"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+3/Xorg_xkeyboard_config.v2.27.0.i686-linux-gnu.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "i686"
git-tree-sha1 = "c3e9b81a152fb7f336c0ba8fd3103e900d0b185e"
libc = "musl"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "66419c2a3eca641b3506ba3a38fd49607e443a7350344ec50799872411102f04"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+3/Xorg_xkeyboard_config.v2.27.0.i686-linux-musl.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "powerpc64le"
git-tree-sha1 = "ee91fdc5f7f520ca6a65f4d515571fcfa3fadd3d"
libc = "glibc"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "0faf58807d87265e926d0cfa8382ba31110ae3e549bd422a096553803a201f52"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+3/Xorg_xkeyboard_config.v2.27.0.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "x86_64"
git-tree-sha1 = "be58fe5ecba3c97f24d6d6d13540b73f19c73e6f"
libc = "glibc"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "39640762597118365679c1c5a509804cefce0c4d79fa7c0af4f1f2b5e8d0d50a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+3/Xorg_xkeyboard_config.v2.27.0.x86_64-linux-gnu.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "x86_64"
git-tree-sha1 = "dfd7242517750f383b366d5f3f8c22f9a24bd991"
libc = "musl"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "9380ceb09b246f63a6e70fefc2c882c7ea8588a30806015f0c87c37848c1d795"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+3/Xorg_xkeyboard_config.v2.27.0.x86_64-linux-musl.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "x86_64"
git-tree-sha1 = "858db472fa451bf7299caa806590cab1992e6f40"
os = "freebsd"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "dea9fd2519681ef192b43f3649ddadeca42f9073c3b9e5ce8ebbd8d68ffa7b58"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+3/Xorg_xkeyboard_config.v2.27.0.x86_64-unknown-freebsd11.1.tar.gz"
