[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "dc05b28dac6c679cd210b4dc7562bfdd07c4344c"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "35d7c90feefedbb5333305ceab39b495a63d80d2a7ab0f59c7f5d7cdbab4f449"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+3/xkbcommon.v0.9.1.aarch64-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "9b9b2aaf28775406a3208534c56b4cee4c404355"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "9d092ee71e79d77c4b5adc4adb8cb7f9fd58706f77e97066d5f4e052f72e60bf"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+3/xkbcommon.v0.9.1.aarch64-linux-musl.tar.gz"
[[xkbcommon]]
arch = "armv7l"
git-tree-sha1 = "b728f2f211146de5c27c83ffc08fd3c1e4c5a966"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "a8914cec96a76c981be6cd31617d8f05c58e0700c940e978616c9b7b90e60ff3"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+3/xkbcommon.v0.9.1.armv7l-linux-gnueabihf.tar.gz"
[[xkbcommon]]
arch = "armv7l"
git-tree-sha1 = "106bb8645b543aaac25bfa8fff58de07dd2d5245"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "392af7cc6d8977d219214e8eef0d61f22af029f58b0ca5403f2b6565a9c7c2ce"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+3/xkbcommon.v0.9.1.armv7l-linux-musleabihf.tar.gz"
[[xkbcommon]]
arch = "i686"
git-tree-sha1 = "f455f1173919dd82a5a27ef411fbfe6e5b435530"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "55a0d84b59559768f5ce2b7c5c6ebd8018f2f3a3fa4a755026eb75f857c92d19"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+3/xkbcommon.v0.9.1.i686-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "i686"
git-tree-sha1 = "cb28f2ed6476b23bced2443edd6f12ff58a1e75f"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "c3cb95691dd5e88bbd2a666a805da9e9545dedf5d716247d825d8376c1fdffce"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+3/xkbcommon.v0.9.1.i686-linux-musl.tar.gz"
[[xkbcommon]]
arch = "powerpc64le"
git-tree-sha1 = "be36a40b7b80249fc71f2c6678e04e2ea87546b5"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "6936a9c81928c04e238a38a35da91b3aaa9222d6b51dbc71b9e1569c0eff7340"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+3/xkbcommon.v0.9.1.powerpc64le-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "2e56e632e959bc09783ed0e5e6501cd75845385e"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "6523c8016452710537f1e402e883cc67579632c6e9575dd21176429d5466cd5a"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+3/xkbcommon.v0.9.1.x86_64-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "3fd33df7aeedbfa591b1c65cf31f280b4fc81283"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "d748492c988f8b2daeba349881dccaae8c189549996e9fc4d495bc15eeae48c5"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+3/xkbcommon.v0.9.1.x86_64-linux-musl.tar.gz"
