[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "40189674accc58b51c55bf729a02115083261d38"
os = "macos"

    [[gdk_pixbuf.download]]
    sha256 = "79bd690d95257dfe3fae7c737bd88e59d33e7d931af680dc030732ea218d4d22"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.aarch64-apple-darwin.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "ddf38ba5b3790ee5a6b4ef8b9a8fceee6701b880"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "c4f729d5512d25ec869040e1cdcfec6455fb6f2e37a9166e600529308e15fae7"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.aarch64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "e45c6c38a2bbcc5039f6d64a5f66d6f1baac159d"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "71b5a9e5f5fa31bba250f74d577adb74b9076fb8b6ea7fcba900e7774bc0cb6b"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.aarch64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e97e195562b225285bb707fa7f702850267f2fce"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "9578dbadbe2098f7b6a1dfe1fd02a430a3bb39d3c37fa170ed552a56befefb54"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.armv6l-linux-gnueabihf.tar.gz"
[[gdk_pixbuf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0c38306c0773fececfb95f130090204bb2b9bfe3"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "41becdd1bf7e469e9b83288af5da15240ad199f9ca60ce500820b4d30ca6ff48"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.armv6l-linux-musleabihf.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "751b95f1562104474e94892774b823755056583f"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "89aac5b041098d18bfe9c7355418136a7ca1a69e07eb45531df55e85373cacc9"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.armv7l-linux-gnueabihf.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f344e903183f6229cd09005520bc3a35d211f288"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "509d1992a079c4872b1231bf004d39a0bd334bdb728c071431c6f38733c388a9"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.armv7l-linux-musleabihf.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "adb3741d7fe0d0ef6235ed037b888a2b58053652"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "4d7483a80fd932375ef4afe8b535d7e9bf6a3e0b2a424df61cff63e997953496"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.i686-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "dcc3185651732afb387133cf81c2bd3bf03e497d"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "0b9c3cb0df56a96d643192f0759338411368c46fe7d30683406d228fabfe0023"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.i686-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "4afe4ef76283933c8d32e21ba014d9dd09d4b1b2"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "2263219aa90b427e98a9ddef595216d386fc85e1a7ee16e9bebc130aff373d50"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.i686-w64-mingw32.tar.gz"
[[gdk_pixbuf]]
arch = "powerpc64le"
git-tree-sha1 = "d245a6784a5737c54720f68958efe625aec7c717"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "a77c9371224481b08513f8f6bde4bac0a40f47bbe466e8ebc2c926f1499124b4"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.powerpc64le-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "9090507139dbc8177d94d4d2bba927770c698c6f"
os = "macos"

    [[gdk_pixbuf.download]]
    sha256 = "9a1090c99832382ac57b0e61cbe5a2a4a768be7b3c9558bfd1a587d94d6c40d5"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.x86_64-apple-darwin.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "baea42656fac5a87db7b3ad98b14ce11a454579e"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "de68c0119a48ee3442d45768068e06f7aafb59489f7986bb8b010bf715f98018"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.x86_64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "b0eac42ea83731b6d0fb56b701f3c05be251382f"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "bf8232622a798a0f7fde576611dc4e64ca5401c145137f9c2a2dbf11d2a2f498"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.x86_64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "8635a9b318029366903d2ecd59f25547210a8927"
os = "freebsd"

    [[gdk_pixbuf.download]]
    sha256 = "32da7b39cbf82895e1b0c04e3fb63b515edeed2ea7ea1fc623277776caa0fc3c"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.x86_64-unknown-freebsd.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "5eb2a8ff5067bf1ef21b4130444d418b5a0d23d1"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "c6322f579bf3efd522730cb4845bbe1c84cdff3530beebe71ae648f29a8b6737"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.6+0/gdk_pixbuf.v2.42.6.x86_64-w64-mingw32.tar.gz"
