[[fzf]]
arch = "aarch64"
git-tree-sha1 = "0f2936bfdb9dec360670856099a29e566b3c2db5"
os = "macos"

    [[fzf.download]]
    sha256 = "87f492c10c6022fff4455cf227a75804dea020d467c252a0b038f5caa10540fa"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.aarch64-apple-darwin.tar.gz"
[[fzf]]
arch = "aarch64"
git-tree-sha1 = "092aca4db63ee327404a24d08c67c91386634fa5"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "5bdf79da1b85682694eb2831a911c9f32ff5fdeea158b40c18af5de4f6bb155f"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.aarch64-linux-gnu.tar.gz"
[[fzf]]
arch = "aarch64"
git-tree-sha1 = "7baa05efb7738816505f953ef27ec0a22a5b06e1"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "d6c1abff4ca6a3a29ab073dbe50c6ad277e045fe7aa875cba7cfa5e1f346ffd6"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.aarch64-linux-musl.tar.gz"
[[fzf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "67ce262416c1fd528bc8e66401b7e06d5afc389e"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "9c8e76371e088bb62707a53ad3433ca3e6e9ccfd57cf5da61dde6b8ba8ab09d1"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.armv6l-linux-gnueabihf.tar.gz"
[[fzf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "29178bb940866b842db9bd4011bc5f16d5b53de7"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "2afbdf308a80b55f91267b92275fdb481407021686b5422d0b2b86a49d0bc246"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.armv6l-linux-musleabihf.tar.gz"
[[fzf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "97e9c0cc7a501029db8210ab03893b5259844678"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "f9c20c770075b64ec6e61fc5e7b1f86540abcfe35e36fca6cfa3b107a76b8909"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.armv7l-linux-gnueabihf.tar.gz"
[[fzf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f426b4d7100838749e6b76b96501e401d78a0179"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "89e1d69db4f8f527b592a5e68941fec5fd1a837de02c29e616fe30a703eb122e"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.armv7l-linux-musleabihf.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "aeb6f69298260de66a747b2ff598818a3bb7f003"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "a2dfb0fbd7524dcf1575c39ce8261ed51d1ce4b150a1db6243863573c7d03a11"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.i686-linux-gnu.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "976d9fb87d4a4f01edac5ad1c1a003f43f6d535a"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "7d83bbceb43706d13763943a8212b3c4ea0d13e5deb550836c36647b0a1efa47"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.i686-linux-musl.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "b991f9f83905f8f88974e6bdbcc595c65ccb38ea"
os = "windows"

    [[fzf.download]]
    sha256 = "a73a28e9de915a4a596aca86d06993f3a5921f66717c30f4303be53202615264"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.i686-w64-mingw32.tar.gz"
[[fzf]]
arch = "powerpc64le"
git-tree-sha1 = "42044a0e5d3a1f3ffcddb5be6d03bac1b943d6ae"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "3738d6a657eb2385c610a46c2ec31bc4f77078a7805c6f65e1315b1858f446da"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.powerpc64le-linux-gnu.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "b80967f20b20d920f01f45b24bb1afb5829d035c"
os = "macos"

    [[fzf.download]]
    sha256 = "092e3b11decb2139e5b51593a60f945613ddd78bd57113d5ee1bb67e16cfa8f9"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.x86_64-apple-darwin.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "6248cb1f54b1805fa1eaeeefc0f2d75f4435e69d"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "d6be08bcdab0bd2724693350698e96a307f22aa728fed1a6805d4364e280ba4e"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.x86_64-linux-gnu.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "e266d08a1e7e1e7aae3964289ba1344155d8f480"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "daa0e5aff37854379800ebb65b17dbc5228d30a123b04411e1f1797783986bf7"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.x86_64-linux-musl.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "52b05a7c8f722c961231d59ecb3410f5205504bc"
os = "freebsd"

    [[fzf.download]]
    sha256 = "bd2ca9b580c2307b7772c02cf9b4dac85efba51a1c1419721300a77be8b53e65"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.x86_64-unknown-freebsd.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "f6c03516faa072e36705d507fd333114e66ca189"
os = "windows"

    [[fzf.download]]
    sha256 = "7ba849a35990c3784932e6795f212425b8d8d860024d8b40192895b8e15b10d6"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.x86_64-w64-mingw32.tar.gz"
