[[Xorg_xkbcomp]]
arch = "aarch64"
git-tree-sha1 = "cd32f496185ad24c52855476ccd44c92817c1dcf"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "834a47cad391f6747e0c779ba68d9e923206b3c3d1f51ba91ebde2a5f123c0df"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+3/Xorg_xkbcomp.v1.4.2.aarch64-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "aarch64"
git-tree-sha1 = "05a1129cff5a044b35d7fec2bd7a0f393020d371"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "e13e0eb36ebb3e4f1f704f6c12ad8af3cbd989c255545b70215bfb02ab98c2e9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+3/Xorg_xkbcomp.v1.4.2.aarch64-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "armv7l"
git-tree-sha1 = "149f56779ad4c07e431423e54db98db468f85816"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "8d0ac2fdb578b7636ad0f59eca0975f7e1f3bde6ec787ac93a4d4b2b294148be"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+3/Xorg_xkbcomp.v1.4.2.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_xkbcomp]]
arch = "armv7l"
git-tree-sha1 = "81e5286ed709a5db93e232e0ad67646b0a165005"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "240031ee7af43dc3b9274f6048e460c526c382385d89b5581adbe8d7b1f89834"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+3/Xorg_xkbcomp.v1.4.2.armv7l-linux-musleabihf.tar.gz"
[[Xorg_xkbcomp]]
arch = "i686"
git-tree-sha1 = "fbc955edb8f2d02101959cc46591cab82680810e"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "897da6c1af60bb28839b615b0d73ae6d9453529dcf3fd8ec261fa437ee70872c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+3/Xorg_xkbcomp.v1.4.2.i686-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "i686"
git-tree-sha1 = "39eee0da23045bca9e504ea2284990765ab0b081"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "ac5bf0346439bf0ab72f31cfdbac5b6a812a81c420f28165e88cb73dcc2fd549"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+3/Xorg_xkbcomp.v1.4.2.i686-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "powerpc64le"
git-tree-sha1 = "82d9c8850379b61a2cd5e1ac4d3999fe79e7b901"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "1910f6110ce48ad41863607b12e1bf73279c73b1cc059e8228d505153feec39b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+3/Xorg_xkbcomp.v1.4.2.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "2022ba6725de1af78cae27ce0d5e8c105e9ed192"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "fadda48d06b79e4dfd6f5803e09f42e924e6fef9ceeb250cb4963e300d19969a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+3/Xorg_xkbcomp.v1.4.2.x86_64-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "45dffeff5d5b7da5dc4fae616905e0ed4b5f8173"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "10845de72a8426c26353d2509ddc585800a9d164f446e0a28a83fbc075acdf88"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+3/Xorg_xkbcomp.v1.4.2.x86_64-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "29655bd5124aec986e47050bd470dfa5030e80d4"
os = "freebsd"

    [[Xorg_xkbcomp.download]]
    sha256 = "dff06346d6ed3a9211f25c675eee9453a50edc163565b30ea40ab1ddf563c210"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+3/Xorg_xkbcomp.v1.4.2.x86_64-unknown-freebsd11.1.tar.gz"
