[[PCRE]]
arch = "aarch64"
git-tree-sha1 = "51a8f70290629b54eb4d03d3010eaeb54192f0d8"
os = "macos"

    [[PCRE.download]]
    sha256 = "6aee6ed49e9396ba8bb9065d8273c720b333687d79cb2e58938bff0427e62db4"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.aarch64-apple-darwin.tar.gz"
[[PCRE]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9008a06170e50ac2b3e9c236c2d94de26362336a"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "3ecb16768f0665de128f92e326d6b518a04ea8ff4ef2b46e76b7f067812fe784"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.aarch64-linux-gnu-cxx03.tar.gz"
[[PCRE]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "142f20230e68988b2002804702598e5d66d525aa"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "9add99c53a452ed102458ed41c28a3a0a7d8bde81cdc96136b964bb74ee66606"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PCRE]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26a7c13d681776c14d7561a30e7fc4aa57d1c058"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "56658d0ff2bdd291727417af4b90803d35a35b4d3207e107294deb6c72d567c8"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.aarch64-linux-musl-cxx03.tar.gz"
[[PCRE]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa7fe2d2f7497adbabbfd43db271f6452ca5bdc7"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "6258f4dc2cb7754fc89a88a15249ffc7d2ee409246cdc1c933609284ce680fb1"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.aarch64-linux-musl-cxx11.tar.gz"
[[PCRE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01dcf77dbfd322af52f00c39ea31cf9374ae6c75"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "6d44a4074c519f1ddeffe878270c9abff7749541629ac7e3193c9eb70c699194"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PCRE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd16f4ae2ac58eb3cf53f5a2f5af0a77ec9289b7"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "c7dabba7219664c1d643534b99d79a98034ab07843cfe21db3d20cd71066d6fc"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PCRE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65d26c29c8e91d5bba03c70831cdae205a8c4436"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "7f172950d515eea298ff2c89c98b948c7bd3e93aa1ae5ce61ac11ae79b42fb54"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PCRE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6877d203d13954cf586799b929df665cadf640f9"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "2d7d0293fe41942662e47226174f9a33f32f6eda0d566232cb92285dd4268707"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PCRE]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d2f1af354c37ba411fc4ae93c383c3264f0b96e"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "4f8429424275e59b544194b258ab4f74ef8f314d9e8afc354d703983194ab74e"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PCRE]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "891aab35d133db0b55d82e8b1fa92b97dbeefb98"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "b50f228bf88ee1df51011f5e335d9955651c37df2c946e7ac9c595e1d7ea7251"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PCRE]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adb13849282034f997fa16f4e48973476be5e0d3"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "5bc328cef4cd69a8e1a1dcd47dd076034b820d51cb2ee8d9a050a2fc3db6e11b"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PCRE]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6f78c79682d1f1aa97543d04496f1c85f2e0043"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "90fdfc2354c40d9a362bb7f2c31b8e8f0116f83f0c63a00268e866ed4bde3ec7"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PCRE]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6f8794c68fd38f8d47c5cc90647b7c443ca510d"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "1b3d6ee8c0b28aa9a29965444f064c73c5809e8f9bda6ac16a1eee2a349c96a2"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.i686-linux-gnu-cxx03.tar.gz"
[[PCRE]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f92cde295b24a4cd7029e126bc65cd9694d2c08"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "a19b57b26835aa4472d7810d29e4fb224787db6b220f8d27fe33d923293a4365"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.i686-linux-gnu-cxx11.tar.gz"
[[PCRE]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c100a458c08c93e655dc1df6cb8f8110310199f"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "711ddd23fea7346ca96093e4883866507819d322314f0856a593540dc5073463"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.i686-linux-musl-cxx03.tar.gz"
[[PCRE]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dab487507f52fd6b9c383ac9b31ea2e0623bfef3"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "f58b08fd8eb732a04709a46f5bce751902305a21a9e1db6df2fca09f8245fdbd"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.i686-linux-musl-cxx11.tar.gz"
[[PCRE]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1980b8f53790e692c4f63f26ce8c684056ef6527"
os = "windows"

    [[PCRE.download]]
    sha256 = "3cedf1718518d5103071456b420e5bc81ece17aef63768ced9b56bbc755d5445"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.i686-w64-mingw32-cxx03.tar.gz"
[[PCRE]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "387fbe96b4b0a311f262d3ba26fad5801eb4bc26"
os = "windows"

    [[PCRE.download]]
    sha256 = "3e22ea105e2f1ec5b8ce12c4fcaad0e8106cf1c62a9c55d22cc87ff4c07a18c0"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.i686-w64-mingw32-cxx11.tar.gz"
[[PCRE]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd495e17012022f37930bb92877aba02963242ea"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "bcb08e33910f551e61a4452145b1ed99abd47f3aef21d99077541adab5ea772d"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PCRE]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35e31d71924a0f46cbd85eec7c5858be446b2172"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "06e7d966778e98b0de16803db9ce28e30b54090d3ed78592fb5b65750735ac39"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PCRE]]
arch = "x86_64"
git-tree-sha1 = "6cc472fe34dbba78d544b6ce97184589371a6665"
os = "macos"

    [[PCRE.download]]
    sha256 = "df09253ebe8373088564c214394acf6e9e405947b9b6d95f9a6ab1d52c8655cd"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.x86_64-apple-darwin.tar.gz"
[[PCRE]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "403b72d7ff928518808f77d7e3a16cfd26b7d739"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "0bb0efe8254c0f2a358cb2c349d33445e690141097efc74027994bdf2f9605f4"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PCRE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17314d4057d189dbe9a4cbb1dc839b541d70fc29"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "c9224f6abc074674c2a3f0635e51421e181965107e7e624239e9da8e7f11dedf"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PCRE]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "718d39b4d6ff9af909651b5df4f74254ebd2c5b3"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "34d23c5ef45595506a819e8f3df9ef14178dae95a4521c252ca619b69b8e79f2"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.x86_64-linux-musl-cxx03.tar.gz"
[[PCRE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3942b5afea43004b6396c12acab77cc91ebfc7e7"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "7cc5de308166c0b56d2430a5402191ae223aa22055c53adc93c99652c63f37ba"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.x86_64-linux-musl-cxx11.tar.gz"
[[PCRE]]
arch = "x86_64"
git-tree-sha1 = "e3b7d65f31c09fbe23957ccc6a89556684559e0f"
os = "freebsd"

    [[PCRE.download]]
    sha256 = "8d7dbb694f070d468f5170cfff7ba111000cc040c1e09bdce12a6e1cc68a48cc"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.x86_64-unknown-freebsd.tar.gz"
[[PCRE]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa60759fc345be5453e7c4bd93df3ba72ebbdb69"
os = "windows"

    [[PCRE.download]]
    sha256 = "1ee484b66e54a850671a400ef5124187d2c1b1034b663d9019fbb00de057a250"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[PCRE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e6cdd29fca31b08026313af46c1db0c724ebbb2"
os = "windows"

    [[PCRE.download]]
    sha256 = "917a5b460c17bd3089a31d98c5cc9dd7e9666d4dcb7edec7e072f8e4ae22abde"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.44.0+0/PCRE.v8.44.0.x86_64-w64-mingw32-cxx11.tar.gz"
