language: julia
os:
    - linux
julia:
    - 0.7
notifications:
    email: false
after_success:
  - julia -e 'using Pkg; Pkg.add(["Documenter", "Coverage"])'
  - julia -e 'using Pkg, Coverage, ArnoldiMethod; cd(joinpath(dirname(pathof(ArnoldiMethod)), "..")); Codecov.submit(process_folder())'
  - julia -e 'using Pkg, ArnoldiMethod; cd(joinpath(dirname(pathof(ArnoldiMethod)), "..")); include(joinpath("docs", "make.jl"))'