[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "0a4b687c4e66e06fd6a9a83519cff9cf964a894a"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "94ce56b168f917eb3d6d8d3354f766b0e6ca722cfe6285ba2b375b34840cf2ae"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.35.0+0/Libmount.v2.35.0.aarch64-linux-gnu.tar.gz"
[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "a2d9c5f646ec33231ee7c4c61075a4f38432021b"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "93711689a8e66d1bc525e13b42bed190907b1090f3808a55bab9e2afbcbf283f"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.35.0+0/Libmount.v2.35.0.aarch64-linux-musl.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c18c33fd0ae69602893f1561b55f9314987e1206"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "c4c0c2bff5861871f690531d9f56f5c8dbc2ab49549ab768fc0d899f00934ffd"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.35.0+0/Libmount.v2.35.0.armv6l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "114dfb39ceaad07b4ce941015468fbb19ed26ec7"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "5a052d7dc1415c6ba126096c233fe4abed260daba8ce22d2ebc27c1b0dcfdde5"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.35.0+0/Libmount.v2.35.0.armv6l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4efc0c5aec44fa5f69ad22c29b76ba668e61eead"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "ad4769919437b4a3ce3bfedaa182d82a78a5edc123f821c5605849d9adb214e6"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.35.0+0/Libmount.v2.35.0.armv7l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aa41b3f3d43e6ab0e8359f3adee1d6b7b4568c97"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "6ecd76626573084d69e0c9658d4004d258c1c0a0e64616d4c2f21c5ecd1fad53"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.35.0+0/Libmount.v2.35.0.armv7l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "c78d287fba390d27403b67892a053d0c837985c9"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "e45a5c304345aac91d1b3f17b80d4f73bab6622398f0e1579b0d18b5b9ab942d"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.35.0+0/Libmount.v2.35.0.i686-linux-gnu.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "09d0460cc81f235d1a8dcf0595da8787da436db4"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "94febd803f2bedce4d0d60596972083e9135893bb5a796c751b87601a5e1f12f"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.35.0+0/Libmount.v2.35.0.i686-linux-musl.tar.gz"
[[Libmount]]
arch = "powerpc64le"
git-tree-sha1 = "eaf3b217d1267d095ef391d55d44a410e6664037"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "ca893b39eb7c3e8141e35d29b5740f1b504abd502f670505a687d905d3fe4bbb"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.35.0+0/Libmount.v2.35.0.powerpc64le-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "5a508a62784097dab7c7ae5805f2c89d2cc97397"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "1db5da71d47f0284a7ad7fe3eb0faf481649e89015a9d5c31da340e9170b1b0d"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.35.0+0/Libmount.v2.35.0.x86_64-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "715f9c0bcc9d437831979a95157668332d98a805"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "801c026092820b2f8bb77b0cf6aa8ae9515c530919203825d387d9b38cab7185"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.35.0+0/Libmount.v2.35.0.x86_64-linux-musl.tar.gz"
