[[libpng]]
arch = "aarch64"
git-tree-sha1 = "b917751a0a1532e56881e471e0f9b441460f2295"
os = "macos"

    [[libpng.download]]
    sha256 = "73fd35dce88a7062a5d8c6c18cec2e50dfc741edb461720f9a272fefde6d557e"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.aarch64-apple-darwin.tar.gz"
[[libpng]]
arch = "aarch64"
git-tree-sha1 = "5be693c9b65e722e967d31940d5f3fb3d9429cba"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "3a36a5e1e3ec66d4a5a4b4c399d609c425ff0c52411011ffb70f7d1660f9dbec"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.aarch64-linux-gnu.tar.gz"
[[libpng]]
arch = "aarch64"
git-tree-sha1 = "76205af66f00fa4220c1c82d5fef04aa1777d88f"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "ea27b07e1010cf8e075d75a8688c547b2d72db08b0056fa47e6630d905f0092c"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.aarch64-linux-musl.tar.gz"
[[libpng]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "57cc9b6817be60ab2100b4e353377061c526a9a9"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "e78d80afeccb3f60f4c1cf4d36912a2999f45bf263a27c5bfb788bb2cfbd17b1"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.armv6l-linux-gnueabihf.tar.gz"
[[libpng]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "71e4877c8afa59ac0aa4dc158ce82ace0581b399"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "59cdb53f91c7e29893a441b406598ff4eff66caee26a94cc40946f2026919f6c"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.armv6l-linux-musleabihf.tar.gz"
[[libpng]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0b39e3bc8d7b7834233774186dc78b31796ee9cb"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "2e0f7354e5763202762f0c6168fdc550ae230179ea0ef7c87002b236111c2619"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.armv7l-linux-gnueabihf.tar.gz"
[[libpng]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cea0e4169763e2dce7c33b4c609ac2dbf461760d"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "e30721490903479446f6d8e749724798d76e386718f1311fbd08e484eded3db2"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.armv7l-linux-musleabihf.tar.gz"
[[libpng]]
arch = "i686"
git-tree-sha1 = "0e76428090642068085662bf846f11b9cd2bfee2"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "11ee0a74b017eacb57fd8b3d3b00894ef8f7b1c7bf642fae4f916a84764f7053"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.i686-linux-gnu.tar.gz"
[[libpng]]
arch = "i686"
git-tree-sha1 = "b424105b169f78aec0768505cd96dba0ec46c9f9"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "5d0fa7791788070bbf777adbff48ea38bcc5394ddd3a867290fe4c76d87e5195"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.i686-linux-musl.tar.gz"
[[libpng]]
arch = "i686"
git-tree-sha1 = "e83986c5aed8946a3fa660051544abd2ca686d0e"
os = "windows"

    [[libpng.download]]
    sha256 = "9a0f1838b1a7eaeebb681d2bc49e7cb396817a1494cd884bc1fa30e9a3ce24f6"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.i686-w64-mingw32.tar.gz"
[[libpng]]
arch = "powerpc64le"
git-tree-sha1 = "51bb35eeae8b3739fc6e2233edb0fd9c0bddff49"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "31cbb961ba3ac2cf765bbae583c116fb82e9fdb8a9e7e048e6c714be956dac50"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.powerpc64le-linux-gnu.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "9194d75745cbb36d5b00e2b1891b2ec6e8c1e2b5"
os = "macos"

    [[libpng.download]]
    sha256 = "bd65b343cf374c62769b76b843ec2af9664dc87774dcc22a02dc7d5bc93bb462"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.x86_64-apple-darwin.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "ddfc455343aff48d27c1b39d7fcb07e0d9242b50"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "444268a49548a199d471769bd2d6438fd43b61597c2511249d34b300d19ecff2"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.x86_64-linux-gnu.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "ddaf857f200f4411337dd0493df9f25929a87282"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "1179ad3d7663dc8eb49895795b4bb6cc1dde8408e21c8eba39f88545aee2c708"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.x86_64-linux-musl.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "b4a38a91e06f50c9d84f85771a583fb24ffd7cca"
os = "freebsd"

    [[libpng.download]]
    sha256 = "a96b6d2bfd3dc05f8a614361afd39ece261257e34e3b6eb5809957b848b2294e"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.x86_64-unknown-freebsd.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "72037f1415327f12277eed0521c861517630a0ba"
os = "windows"

    [[libpng.download]]
    sha256 = "6c2666da0aa1d8075709982c776d773c51999b678d9ba839df27caf031c778df"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.x86_64-w64-mingw32.tar.gz"
