[[Xorg_libXcomposite]]
arch = "aarch64"
git-tree-sha1 = "c0bc7d1c7fa5d6e454d8c211b324f348db51ae8a"
libc = "glibc"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "3b5498c916d9fe7f499ea68f2691c127ead0a59f0ab15d03fe5d961dc21d4a16"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.5+3/Xorg_libXcomposite.v0.4.5.aarch64-linux-gnu.tar.gz"
[[Xorg_libXcomposite]]
arch = "aarch64"
git-tree-sha1 = "413006492ae09a5b5df18016bafd98c96342256f"
libc = "musl"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "db2cec47506a645f1d8b417710c61e23636ad0bf8170ae63805ab0de14b8d6cb"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.5+3/Xorg_libXcomposite.v0.4.5.aarch64-linux-musl.tar.gz"
[[Xorg_libXcomposite]]
arch = "armv7l"
git-tree-sha1 = "60ada53b671ac501b740b885839e594e14e11912"
libc = "glibc"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "2cb5f2aa81ed0af63980507df1402a7d1b6d60d28f177ced797fd9a1c4944b6c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.5+3/Xorg_libXcomposite.v0.4.5.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXcomposite]]
arch = "armv7l"
git-tree-sha1 = "9d1dc5dcc523903df6de1f919b3124068e0c3562"
libc = "musl"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "3bb73fcdf185946c1e16c8b1154da6e320046caa7081ba3fbc15ff5245fa13fc"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.5+3/Xorg_libXcomposite.v0.4.5.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXcomposite]]
arch = "i686"
git-tree-sha1 = "b06f6ff398429ae5e3a4d858804f35535c3345a6"
libc = "glibc"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "8131074a5ad8b0ef61ece7969c832d5ead2aa355c359cef9fd1d8baca8168731"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.5+3/Xorg_libXcomposite.v0.4.5.i686-linux-gnu.tar.gz"
[[Xorg_libXcomposite]]
arch = "i686"
git-tree-sha1 = "da6e8fec2682d4c1d7210cf581d081fa5baf74ae"
libc = "musl"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "a567054202dbaf362800b0123d40482178a9cde6f2a72fd482e47e4ff7da91b3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.5+3/Xorg_libXcomposite.v0.4.5.i686-linux-musl.tar.gz"
[[Xorg_libXcomposite]]
arch = "powerpc64le"
git-tree-sha1 = "5028e4570dcb241e3fe6cca9061d256073a434cf"
libc = "glibc"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "c1681c5c8a4d5dd7460e453b00d3e574b85f37895df07a1cc6066a0e82c9f6cc"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.5+3/Xorg_libXcomposite.v0.4.5.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXcomposite]]
arch = "x86_64"
git-tree-sha1 = "25fec041315dc9336379a02d310f1b8d9c27eb0f"
libc = "glibc"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "b1570d9344f143f63eda36ef02edc1f7b11c260764d9b23a3daeb968af2da986"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.5+3/Xorg_libXcomposite.v0.4.5.x86_64-linux-gnu.tar.gz"
[[Xorg_libXcomposite]]
arch = "x86_64"
git-tree-sha1 = "1242062404c37ea2e02e2256fb0e69a19d954914"
libc = "musl"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "1a55b8243f5d5f9f605a0a4a89e59ed767852d813779e5b021d1b20d3e5f97b8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.5+3/Xorg_libXcomposite.v0.4.5.x86_64-linux-musl.tar.gz"
[[Xorg_libXcomposite]]
arch = "x86_64"
git-tree-sha1 = "27a789daa4b829749f95c9d14d07f8690bdf1318"
os = "freebsd"

    [[Xorg_libXcomposite.download]]
    sha256 = "62f9fe7406b88cce446d53ad3bc41cf5c4e838a83b7c97f0e6b9e72a21bc10c9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.5+3/Xorg_libXcomposite.v0.4.5.x86_64-unknown-freebsd11.1.tar.gz"
