[[at_spi2_core]]
arch = "aarch64"
git-tree-sha1 = "7aa1017f803e77cbef42d947f18d38ed4779d692"
libc = "glibc"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "fc7480f5d2ee5a5385dfddcc63252fdead2fe60cb2446259416529955f225b01"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.34.0+3/at_spi2_core.v2.34.0.aarch64-linux-gnu.tar.gz"
[[at_spi2_core]]
arch = "aarch64"
git-tree-sha1 = "5cece9addb96f47643aa47829abba8ec3fcc31e8"
libc = "musl"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "2f25a0c7d49b5c8f2f5167e9994f1186819bc8f2932335d3ec63c444a60f881f"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.34.0+3/at_spi2_core.v2.34.0.aarch64-linux-musl.tar.gz"
[[at_spi2_core]]
arch = "armv7l"
git-tree-sha1 = "824d9ecd68c16ccfefc9491cb08764f1307e6838"
libc = "glibc"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "b85e820c648a612c42ec767e9d1addab810a92fc4032044cb3a86460b7aa1135"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.34.0+3/at_spi2_core.v2.34.0.armv7l-linux-gnueabihf.tar.gz"
[[at_spi2_core]]
arch = "armv7l"
git-tree-sha1 = "edb49ff904aed1ab501629167a34f2b6273c12ee"
libc = "musl"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "9f15c2b6719d5771d9911711dcf8ad3a84530f5cde8a481c7ee18b40eec4c6ff"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.34.0+3/at_spi2_core.v2.34.0.armv7l-linux-musleabihf.tar.gz"
[[at_spi2_core]]
arch = "i686"
git-tree-sha1 = "665b784e530de6c3e509bb0fba104cfef03cb714"
libc = "glibc"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "8ffaf4992972f0da1c5d2461e8e40295faa9c797f89c9f4e2bb6336964891cb3"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.34.0+3/at_spi2_core.v2.34.0.i686-linux-gnu.tar.gz"
[[at_spi2_core]]
arch = "i686"
git-tree-sha1 = "c2bb336dd941d3c234e110a12a64e9097406e14d"
libc = "musl"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "e5aa9c4534ba072fd8668fd4b96214ca8be811e8e2d0e561607cbc239dab0f5d"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.34.0+3/at_spi2_core.v2.34.0.i686-linux-musl.tar.gz"
[[at_spi2_core]]
arch = "powerpc64le"
git-tree-sha1 = "6c6582e668d6fb481243b750a6640ee6fdb9cb91"
libc = "glibc"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "082367ace995f40a9a634be70930288c3ee530fe5179a21caefc692997e1e094"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.34.0+3/at_spi2_core.v2.34.0.powerpc64le-linux-gnu.tar.gz"
[[at_spi2_core]]
arch = "x86_64"
git-tree-sha1 = "0559db48d752dacf6747780530ca11c045af5d0e"
libc = "glibc"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "4532cdeefe9eb34382f774252b8a7ec42df4f662b13f7410554e786b7cafaa71"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.34.0+3/at_spi2_core.v2.34.0.x86_64-linux-gnu.tar.gz"
[[at_spi2_core]]
arch = "x86_64"
git-tree-sha1 = "841df5f7873e61be936831236c73325eae3dad42"
libc = "musl"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "0ad5252d7efa3325634f6037dd323b1d68b1acb0cd79229d6dbb007a01e54f1c"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.34.0+3/at_spi2_core.v2.34.0.x86_64-linux-musl.tar.gz"
[[at_spi2_core]]
arch = "x86_64"
git-tree-sha1 = "138a359d99b5e930c570f494e3fa1c7857c43d52"
os = "freebsd"

    [[at_spi2_core.download]]
    sha256 = "90bd9930044fc7894c2c13ed8cb0208a2a8b12b35d868323474528ecdd5d73dc"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.34.0+3/at_spi2_core.v2.34.0.x86_64-unknown-freebsd11.1.tar.gz"
